// saque esta listota para aca pa que no estorbe en el codigo principal

var listaDeAcuerdos = [
    { id: 1, cant: 1, texto: "perfil del proyecto", activo: true },
    { id: 2, cant: 1, texto: "título del proyecto", activo: true },
    { id: 3, cant: 1, texto: "objetivo general", activo: true },
    { id: 4, cant: 1, texto: "sector económico", activo: true },
    { id: 5, cant: 1, texto: "giro empresarial", activo: true },
    { id: 6, cant: 1, texto: "reporte de contribución al PIB", activo: true },
    { id: 7, cant: 1, texto: "perfil del cliente", activo: true },
    { id: 8, cant: 1, texto: "análisis de mercado TI", activo: true },
    { id: 9, cant: 1, texto: "estudio de facitbilidad", activo: true },
    { id: 10, cant: 1, texto: "tabla de proyecciones financieras", activo: true },
    { id: 11, cant: 1, texto: "tabla del análisis comparativo de la competencia", activo: true },
    { id: 12, cant: 1, texto: "tabla del plan operativo", activo: true },
    { id: 13, cant: 1, texto: "tabla del plan general de trabajo", activo: true },
    { id: 14, cant: 3, texto: "diagramas de entrada, proceso y salida", activo: true },
    { id: 15, cant: 3, texto: "listas de los recursos de entrada, proceso y salida", activo: true },
    { id: 16, cant: 4, texto: "tablas de los recursos enlistados de entrada, proceso y salida", activo: true },
    { id: 17, cant: 1, texto: "diagrama CPM", activo: true },
    { id: 18, cant: 1, texto: "acta de constitución firmada", activo: true },
    { id: 19, cant: 1, texto: "matriz de intersados", activo: true },
    { id: 20, cant: 1, texto: "documento de alcance del software", activo: true },
    { id: 21, cant: 1, texto: "diagrama EDT/WBS", activo: true },
    { id: 22, cant: 1, texto: "plan de dirección integral", activo: true },
    { id: 23, cant: 1, texto: "set de plantillas para usuarios", activo: true },
    { id: 24, cant: 1, texto: "software único de pruebas (Testify)", activo: true },
    { id: 25, cant: 1, texto: "módulo de IA para conclusiones", activo: true },
    { id: 26, cant: 5, texto: "reportes de avance metodológico", activo: true },
    { id: 27, cant: 1, texto: "proyecto de inversión técnica", activo: true },
    { id: 28, cant: 1, texto: "prototipo funcional validado", activo: true },
    { id: 29, cant: 1, texto: "plano operativo técnico", activo: true },
    { id: 30, cant: 1, texto: "servidor PostgreSQl configurado", activo: true },
    { id: 31, cant: 1, texto: "interfaz de usuario programada", activo: true },
    { id: 32, cant: 3, texto: "módulos de seguridad configurados", activo: true },
    { id: 33, cant: 1, texto: "diseño estructural completo", activo: true },
    { id: 34, cant: 1, texto: "manual de estándares de proceso", activo: true },
    { id: 35, cant: 1, texto: "reporte de integridad de datos", activo: true },
    { id: 36, cant: 1, texto: "set de módulos desarrollados", activo: true },
    { id: 37, cant: 1, texto: "reporte de validación de IA", activo: true },
    { id: 38, cant: 5, texto: "protocolos de mantenimiento", activo: true },
    { id: 39, cant: 1, texto: "documento de errores (QA)", activo: true },
    { id: 40, cant: 15, texto: "reportes de pruebas unitarias", activo: true },
    { id: 41, cant: 11, texto: "reportes de actualización", activo: true },
    { id: 42, cant: 2, texto: "convenios de asociación", activo: true },
    { id: 43, cant: 1, texto: "presupuesto de innovación", activo: true },
    { id: 44, cant: 1, texto: "reporte de retorno de inversión", activo: true },
    { id: 45, cant: 1, texto: "plan de adquisición de activos", activo: true },
    { id: 46, cant: 1, texto: "tarifario oficial de Testify", activo: true },
    { id: 47, cant: 4, texto: "reportes presupuestales", activo: true },
    { id: 48, cant: 1, texto: "bitácora de administración", activo: true },
    { id: 49, cant: 11, texto: "comprobantes de dispersión", activo: true },
    { id: 50, cant: 11, texto: "balances generales", activo: true },
    { id: 51, cant: 5, texto: "contratos laborales firmados", activo: true },
    { id: 52, cant: 1, texto: "programa de capacitación integral", activo: true },
    { id: 53, cant: 1, texto: "sistema de evaluación", activo: true },
    { id: 54, cant: 5, texto: "perfiles de puesto validados", activo: true },
    { id: 55, cant: 3, texto: "módulos formativos diseñados", activo: true },
    { id: 56, cant: 1, texto: "manual de indicadores (KPIs)", activo: true },
    { id: 57, cant: 15, texto: "reportes de entrevista", activo: true },
    { id: 58, cant: 5, texto: "bitácoras de inducción", activo: true },
    { id: 59, cant: 11, texto: "reportes de evaluación mensual", activo: true },
    { id: 60, cant: 6, texto: "contratos de licencia firmados", activo: true },
    { id: 61, cant: 1, texto: "reporte de posicionamiento", activo: true },
    { id: 62, cant: 1, texto: "plan de post venta detallado", activo: true },
    { id: 63, cant: 1, texto: "cartera de 20 prospectos", activo: true },
    { id: 64, cant: 1, texto: "presentación ejecutiva (Pitch Deck)", activo: true },
    { id: 65, cant: 1, texto: "manual de niveles de servicio", activo: true },
    { id: 66, cant: 6, texto: "expedientes de contrato cerrados", activo: true },
    { id: 67, cant: 10, texto: "bitácoras de demostración", activo: true },
    { id: 68, cant: 6, texto: "reportes de satisfaction", activo: true },
    { id: 69, cant: 1, texto: "tabla de checklist de verificación", activo: true },
    { id: 70, cant: 1, texto: "bitácora de control de cambios", activo: true },
    { id: 71, cant: 1, texto: "reporte de seguimiento de hitos", activo: true },
    { id: 72, cant: 1, texto: "matriz de resultados finales", activo: true },
    { id: 73, cant: 1, texto: "reporte de costos reales vs planeados", activo: true },
    { id: 74, cant: 1, texto: "análisis de valor ganado", activo: true },
    { id: 75, cant: 1, texto: "acta de cierre del proyecto firmada", activo: true }
];