// arreglo global para los hitos :p

var listaDeHitos = [
    { id: 1, cant: null, texto: "Tema", activo: true },
    { id: 2, cant: null, texto: "Título", activo: true },
    { id: 3, cant: null, texto: "Objetivo", activo: true },
    { id: 4, cant: null, texto: "Sector", activo: true },
    { id: 5, cant: null, texto: "Giro", activo: true },
    { id: 6, cant: null, texto: "PIB", activo: true },
    { id: 7, cant: null, texto: "Cliente", activo: true },
    { id: 8, cant: null, texto: "Mercado", activo: true },
    { id: 9, cant: null, texto: "Aceptación del mercado", activo: true },
    { id: 10, cant: null, texto: "Proyección de ventas", activo: true },
    { id: 11, cant: null, texto: "Benchmarking", activo: true },
    { id: 12, cant: null, texto: "Plan operativo", activo: true },
    { id: 13, cant: null, texto: "Plan general de trabajo", activo: true },
    { id: 14, cant: null, texto: "Plan de comercialización", activo: true },
    { id: 15, cant: null, texto: "Cronograma de Actividades", activo: true },
    { id: 16, cant: null, texto: "Red CPM", activo: true },
    { id: 17, cant: null, texto: "Acta de constitución del proyecto", activo: true },
    { id: 18, cant: null, texto: "Gestión de interesados", activo: true },
    { id: 19, cant: null, texto: "Gestión del alcance", activo: true },
    { id: 20, cant: null, texto: "EDT", activo: true },
    { id: 21, cant: null, texto: "Gestión de dirección del proyecto", activo: true },
    { id: 22, cant: null, texto: "Plantillas de requisitos", activo: true },
    { id: 23, cant: null, texto: "Diseñar y desarrollar un software único", activo: true },
    { id: 24, cant: null, texto: "Gestionar una innovación de IA", activo: true },
    { id: 25, cant: null, texto: "Gestionar una innovación técnica de IA", activo: true },
    { id: 26, cant: null, texto: "Gestionar el proyecto integral", activo: true },
    { id: 27, cant: null, texto: "Realizar el proyecto de inversión técnica", activo: true },
    { id: 28, cant: null, texto: "Desarrollar el prototipo funcional", activo: true },
    { id: 29, cant: null, texto: "Realizar el plan operativo técnico", activo: true },
    { id: 30, cant: null, texto: "Instalar la infraestructura de red", activo: true },
    { id: 31, cant: null, texto: "Programar la interfaz de usuario", activo: true },
    { id: 32, cant: null, texto: "Configurar los módulos de seguridad", activo: true },
    { id: 33, cant: null, texto: "Diseñar la estructura funcional y técnica del software", activo: true },
    { id: 34, cant: null, texto: "Gestionar la estandarización de procesos de reportes", activo: true },
    { id: 35, cant: null, texto: "Supervisar la integridad de la base de datos y flujo", activo: true },
    { id: 36, cant: null, texto: "Desarrollar los módulos de software", activo: true },
    { id: 37, cant: null, texto: "Validar los algoritmos de IA para el mapeo de datos", activo: true },
    { id: 38, cant: null, texto: "Estructurar los protocolos de mantenimiento y actualización", activo: true },
    { id: 39, cant: null, texto: "Documentar las pruebas de errores y rendimiento", activo: true },
    { id: 40, cant: null, texto: "Ejecutar las pruebas unitarias de los módulos", activo: true },
    { id: 41, cant: null, texto: "Realizar las actualizaciones de seguridad en la BD", activo: true },
    { id: 42, cant: null, texto: "Obtener afiliaciones con socios capitalistas", activo: true },
    { id: 43, cant: null, texto: "Gestionar el presupuesto de innovación", activo: true },
    { id: 44, cant: null, texto: "Realizar la proyección de recuperación financiera", activo: true },
    { id: 45, cant: null, texto: "Determinar el capital para activos y equipo", activo: true },
    { id: 46, cant: null, texto: "Definir el tarifario de licencias anuales", activo: true },
    { id: 47, cant: null, texto: "Obtener el presupuesto trimestral de nómina", activo: true },
    { id: 48, cant: null, texto: "Administrar el fondo de infraestructura física", activo: true },
    { id: 49, cant: null, texto: "Ejecutar el pago mensual de salarios", activo: true },
    { id: 50, cant: null, texto: "Realizar el balance de caja mensual", activo: true },
    { id: 51, cant: null, texto: "Contratar personal especializado", activo: true },
    { id: 52, cant: null, texto: "Capacitar al personal en metodologías y BD", activo: true },
    { id: 53, cant: null, texto: "Establecer el sistema de evaluación del desempeño", activo: true },
    { id: 54, cant: null, texto: "Definir los perfiles de puesto y competencias técnicas", activo: true },
    { id: 55, cant: null, texto: "Diseñar los talleres formativos de la arquitectura", activo: true },
    { id: 56, cant: null, texto: "Estructurar los KPIs de productividad del equipo", activo: true },
    { id: 57, cant: null, texto: "Realizar las entrevistas y pruebas técnicas", activo: true },
    { id: 58, cant: null, texto: "Ejecutar la inducción técnica al nuevo personal", activo: true },
    { id: 59, cant: null, texto: "Aplicar las encuestas de desempeño mensuales", activo: true },
    { id: 60, cant: null, texto: "Vender el licenciamiento anual a las empresas de TI", activo: true },
    { id: 61, cant: null, texto: "Posicionar a Testify en el mercado de la CDMX", activo: true },
    { id: 62, cant: null, texto: "Diseñar el plan de post venta y mantenimiento", activo: true },
    { id: 63, cant: null, texto: "Realizar la prospección de cliente", activo: true },
    { id: 64, cant: null, texto: "Desarrollar el pitch deck comercial de Testify", activo: true },
    { id: 65, cant: null, texto: "Definir los niveles de soporte y acuerdos", activo: true },
    { id: 66, cant: null, texto: "Cerrar los contratos legales con los clientes", activo: true },
    { id: 67, cant: null, texto: "Ejecutar las demos técnicas para jefes de área gestionar encuestas de satisfacción y eficiencia", activo: true },
    { id: 68, cant: null, texto: "Cheecklist de verificación", activo: true },
    { id: 70, cant: null, texto: "Control de cambios", activo: true },
    { id: 71, cant: null, texto: "Control de seguimiento", activo: true },
    { id: 72, cant: null, texto: "Plantilla de resultados", activo: true },
    { id: 73, cant: null, texto: "Plantilla de costos", activo: true },
    { id: 74, cant: null, texto: "Plantilla de valor ganado", activo: true },
    { id: 75, cant: null, texto: "Plantilla de acta de cierre", activo: true }
];